### ISSUE TITLE
执行casia_hwdb的inferrence错误

### ISSUE THREAD

**Issue by henuliulei** [Mountchicken/General-Text-Recogniton-Zoo#2]
大神你的/CASIA_HWDB/inference.sh的  --alphabets casia_360cc \这个参数是不是写错了，应该写成所有的lable吧，这样写就只有这12个lable了，下面是我执行的错误。

.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	size mismatch for decoder.weight: copying a param with shape torch.Size([6018, 512]) from checkpoint, the shape in current model is torch.Size([12, 512]).
	size mismatch for decoder.bias: copying a param with shape torch.Size([6018]) from checkpoint, the shape in current model is torch.Size([12]).

**Comment by Mountchicken** [comment]
你好，这个项目是一个实验性项目，我打算的是把主流的文字识别算法全部囊括在一个框架内，所以会不断更新，但是我的代码能力有限，没办法做到写出一个稳定的框架然后继续在上面加东西，只能不断的删改源代码来实现扩充😂所以每次更新后，如果想要使用到更新的功能，还请重新下载代码（你说的这个bug在新版本的代码中已经修复😃

**Comment by henuliulei** [comment]
OK，期望大佬能出一个可以对整个文档进行识别的模型

**Comment by Mountchicken** [comment]
可以看看我之前的一个rep，用的是CTPN+CRNN的组合，可以实现文档识别[https://github.com/Mountchicken/CTPN_CRNN_ChineseOCR_PyQt5](https://github.com/Mountchicken/CTPN_CRNN_ChineseOCR_PyQt5)

**Comment by henuliulei** [comment]
大佬，我感觉你的训练手写汉字的效果还可以，你有一个是使用了hwdb数据集，我也用了hwdb训凑crnn，发现在验证集上直接效果很差，从没高过1%，训练集达到四十多,请问你训练为啥那么好呢？我这边可能在哪出现了问题呢

**Comment by Mountchicken** [comment]
> 大佬，我感觉你的训练手写汉字的效果还可以，你有一个是使用了hwdb数据集，我也用了hwdb训凑crnn，发现在验证集上直接效果很差，从没高过1%，训练集达到四十多,请问你训练为啥那么好呢？我这边可能在哪出现了问题呢

--
emm，感觉是数据增广出了问题，要不试一试把  train.sh中的这一行 --augmentation IAM \ 删除掉。中文不太需要进行几何变换
