### ISSUE TITLE
空格的问题

### ISSUE THREAD

**Issue by Zsynapsis** [Mountchicken/General-Text-Recogniton-Zoo#4]
作者您好，我跑通了您的代码，但是有个小问题就是得出的结果和GT都不包含空格，但是我用的是包含空格的数据集，麻烦问一下是哪里出了问题了吗？
期待答复，万分感谢

**Comment by Mountchicken** [comment]
Hi @Yidi-2896 
在训练脚本中加入 --punc 即可
https://github.com/Mountchicken/Text-Recognition-on-Cross-Domain-Datasets/blob/d65a752d03040b250acbab754c1ccd9bfa5402ea/scripts/CRNN/iam_dataset/train.sh#L11-L16

**Comment by Zsynapsis** [comment]
十分感谢，已经得到了正确的结果！！
